import Footer from "../components/footer";
import Header from "../components/header/header";

export const metadata = {
    title: "Hotel Grupo 3",
    description: "Generated by create next app",
};

export default function ContactLayout({ children }) {
    return (
        <html lang="en">
            <body>
                <Header bannerImg='images/banners/banner-contact.png'></Header>
                {children}
                <Footer></Footer>
            </body>
        </html>
    );

}