
import * as React from 'react';
import Footer from "../components/footer";
import Header from "../components/header/header";




export const metadata = {
    title: "Galería",
    description: "Generated by create next app",
};

export default function GalleryLayout({ children }) {
    return (
        <>
            <Header bannerImg='banners/banner-galeria.png'></Header>
            {children}
            <Footer></Footer>
           
        </>
    );

}
