import Footer from "../components/footer";
import Header from "../components/header/header";

export const metadata = {
    title: "Galería",
    description: "Generated by create next app",
};

export default function GalleryLayout({ children }) {
    return (
        <html lang="es">
            <body>
                <Header bannerImg='../../../public/images/banners/banner-galeria.png'></Header>
                {children}
                <Footer></Footer>
            </body>
        </html>
    );

}
