
import Header from "../components/header/header";
import ReservaPage from "./page";
import Pago from "./pago/page";

export const metadata = {
    title: "Reserva / Pago",
    description: "Generated by create next app",
};

function LayoutReserva() {

    const Component = () => {
        if (false) {
            return (
                <Pago></Pago>
            );
        }else{
            return(
                <ReservaPage></ReservaPage>
            );
        }
    }

    return (
        <html lang="en">
            <body>
                <Header bannerImg="/images/banners/banner-reserva.png"></Header>
                <Component></Component>
            </body>
        </html>
    );
}

export default LayoutReserva;