import './globals.css'


export const metadata = {
  title: "Hotel Grupo 3",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <body className='body'>{children}</body>
    </html>
  );

}
